const STATIC_LABELS: Record<string, string> = {
  shell_command: "Running a command",
  shell_wait: "Waiting for a command",
  read_files: "Reading files",
  search_files: "Searching files",
  search_content: "Searching in files",
  write_files: "Writing files",
  delete_files: "Deleting files",
  copy_files: "Copying files",
  move_files: "Moving files",
  archive_files: "Working with archives",
  run_tests: "Running tests",
  check_types: "Checking types",
  build_project: "Building the project",
  run_lint: "Checking code quality",
  format_code: "Formatting code",
  install_dependencies: "Installing dependencies",
  inspect_git: "Inspecting Git changes",
  manage_git: "Managing Git",
  inspect_github: "Inspecting GitHub",
  manage_github: "Managing GitHub",
  inspect_processes: "Inspecting processes",
  manage_processes: "Managing processes",
  restart_service: "Restarting the service",
  run_script: "Running a script",
  inspect_files: "Inspecting files",
  transfer_files: "Transferring files",
  remote_connection: "Connecting remotely",
  inspect_packages: "Inspecting packages",
  inspect_codex: "Inspecting Codex",
  process_data: "Processing data",
  inspect_environment: "Inspecting the environment",
  inspect_logs: "Inspecting system logs",
  inspect_registry: "Inspecting the registry",
  inspect_devices: "Inspecting devices",
  inspect_storage: "Inspecting storage",
  inspect_system: "Inspecting the system",
  check_syntax: "Checking syntax",
  network_request: "Checking network resources",
  query_database: "Querying a database",
  manage_containers: "Managing containers",
  deploy: "Deploying",
  update_plan: "Updating the plan",
  js: "Running JavaScript",
  computer: "Controlling the computer",
  view_image: "Viewing an image",
  docs: "Reading docs",
  docs_read: "Reading OpenAI docs",
  docs_search: "Searching OpenAI docs",
  docs_list: "Listing OpenAI docs",
  spawn_agent: "Delegating to agents",
  list_agents: "Checking agents",
  wait_agent: "Waiting for agents",
  message_agent: "Messaging an agent",
  followup_agent: "Assigning agent work",
  goal: "Managing goals",
  automation: "Managing automations",
  thread: "Managing threads",
  list_projects: "Listing projects",
  list_tasks: "Listing tasks",
  read_task: "Reading a task",
  create_task: "Creating a task",
  fork_task: "Forking a task",
  message_task: "Messaging a task",
  handoff_task: "Handing off a task",
  check_handoff: "Checking task handoff",
  manage_task: "Managing a task",
  open_task: "Opening a task",
  read_terminal: "Reading the terminal",
  web_search: "Searching the web",
  web_run: "Browsing the web",
  image_search: "Searching for images",
  weather: "Checking the weather",
  finance: "Checking market data",
  sports: "Checking sports data",
  time_lookup: "Checking the time",
  browser: "Using the browser",
  inspect_browser: "Inspecting the browser",
  send_input: "Messaging an agent",
  load_workspace_dependencies: "Loading workspace dependencies",
  plugin: "Managing plugins",
  read_resource: "Reading MCP resources",
  list_resources: "Listing MCP resources",
  inspect_sites: "Inspecting sites",
  manage_site: "Managing a site",
  deploy_site: "Deploying a site",
  inspect_documents: "Inspecting documents",
  edit_documents: "Editing documents",
  image_generation: "Generating an image",
  context_compacted: "Compacting context",
  generic: "Working",
};

export function codexToolLabel(name: string, file?: string, server?: string): string {
  if (name === "apply_patch") return file ? `Editing ${file}` : "Editing files";
  if (name === "mcp") return server ? `Using ${server}` : "Using MCP tools";
  if (name === "read_resource" && server) return `Reading from ${server}`;
  return STATIC_LABELS[name] ?? "Working";
}
